export const ActionTypes = {
  DISPLAY_ALERT: "SHOW_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",
  SETUP_USER_START: "SETUP_USER_START",
  SETUP_USER_SUCCESS: "SETUP_USER_SUCCESS",
  SETUP_USER_ERROR: "SETUP_USER_ERROR",
};
